name: My First Workflow

on: push

jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
       - name: checkoout repo
         uses: actions/checkout@v4
         
       - name: List and Read file
         run:
           echo "My First GitHub Actions Job"
           ls -ltra
           cat README.md

       - name: generate ASCII ArtWork
         run: cowsay -f dragon "Run for cover, I ama DRAGON....RAWR" >> dragon.txt


